import { Trend } from 'k6/metrics';

export const trends = {
    HomePage_open_lcp: new Trend('A_HomePage_open_lcp'),
    HomePage_open_fcp: new Trend('A_HomePage_open_fcp'),
    HomePage_open_ttfb: new Trend('A_HomePage_open_ttfb'),
    HomePage_open_ttlb: new Trend('A_HomePage_open_ttlb'),
    HomePage_open_latency: new Trend('A_HomePage_open_latency'),
    HomePage_open_dom_interactive: new Trend('A_HomePage_open_dom_interactive'),
    HomePage_open_network_overhead: new Trend('A_HomePage_open_network_overhead'),
    HomePage_open_first_response_time: new Trend('A_HomePage_open_first_response_time'),
    HomePage_open_content_download: new Trend('A_HomePage_open_content_download'),
    HomePage_open_page_ready: new Trend('A_HomePage_open_page_ready'),
    HomePage_open_first_interactive: new Trend('A_HomePage_open_first_interactive'),

    challengespageOpenlcp: new Trend('B_challengespage_open_lcp'),
    challengespageOpenfcp: new Trend('B_challengespage_open_fcp'),
    challengespageOpenttfb: new Trend('B_challengespage_open_ttfb'),
    challengespageOpenttlb: new Trend('B_challengespage_open_ttlb'),
    challengespageOpencompletiontime: new Trend('B_challengespage_open_completion_time'),
    challengespageOpenlatency: new Trend('B_challengespage_open_latency'),
    challengespageOpendominteractive: new Trend('B_challengespage_open_dom_interactive'),
    challengespageOpennetworkoverhead: new Trend('B_challengespage_open_network_overhead'),
    challengespageOpenfirstresponsetime: new Trend('B_challengespage_open_first_response_time'),
    challengespageOpencontentdownload: new Trend('B_challengespage_open_content_download'),
    challengespageOpenready: new Trend('B_challengespage_open_page_ready'),
    challengespageOpenfirstinteractive: new Trend('B_challengespage_open_first_interactive'),

    middlemanagerspageOpenlcp: new Trend('C_middlemanagerspage_open_lcp'),
    middlemanagerspageOpenfcp: new Trend('C_middlemanagerspage_open_fcp'),
    middlemanagerspageOpenttfb: new Trend('C_middlemanagerspage_open_ttfb'),
    middlemanagerspageOpenttlb: new Trend('C_middlemanagerspage_open_ttlb'),
    middlemanagerspageOpencompletiontime: new Trend('C_middlemanagerspage_open_completion_time'),
    middlemanagerspageOpenlatency: new Trend('C_middlemanagerspage_open_latency'),
    middlemanagerspageOpendominteractive: new Trend('C_middlemanagerspage_open_dom_interactive'),
    middlemanagerspageOpennetworkoverhead: new Trend('C_middlemanagerspage_open_network_overhead'),
    middlemanagerspageOpenfirstresponsetime: new Trend('C_middlemanagerspage_open_first_response_time'),
    middlemanagerspageOpencontentdownload: new Trend('C_middlemanagerspage_open_content_download'),
    middlemanagerspageOpenready: new Trend('C_middlemanagerspage_open_page_ready'),
    middlemanagerspageOpenfirstinteractive: new Trend('C_middlemanagerspage_open_first_interactive'),

    // LeadershipPage_openleadershipProgram_lcp: new Trend('D_LeadershipPage_openleadershipProgram_lcp'),
    // LeadershipPage_openleadershipProgram_fcp: new Trend('D_LeadershipPage_openleadershipProgram_fcp'),
    // LeadershipPage_openleadershipProgram_ttfb: new Trend('D_LeadershipPage_openleadershipProgram_ttfb'),
    // LeadershipPage_openleadershipProgram_ttlb: new Trend('D_LeadershipPage_openleadershipProgram_ttlb'),
    // LeadershipPage_openleadershipProgram_completion_time: new Trend('D_LeadershipPage_openleadershipProgram_completion_time'),
    // LeadershipPage_openleadershipProgram_latency: new Trend('D_LeadershipPage_openleadershipProgram_latency'),
    // LeadershipPage_openleadershipProgram_dom_interactive: new Trend('D_LeadershipPage_openleadershipProgram_dom_interactive'),
    // LeadershipPage_openleadershipProgram_network_overhead: new Trend('D_LeadershipPage_openleadershipProgram_network_overhead'),
    // LeadershipPage_openleadershipProgram_first_response_time: new Trend('D_LeadershipPage_openleadershipProgram_first_response_time'),
    // LeadershipPage_openleadershipProgram_content_download: new Trend('D_LeadershipPage_openleadershipProgram_content_download'),
    // LeadershipPage_openleadershipProgram_page_ready: new Trend('D_LeadershipPage_openleadershipProgram_page_ready'),
    // LeadershipPage_openleadershipProgram_first_interactive: new Trend('D_LeadershipPage_openleadershipProgram_first_interactive'),

    ContactUsPage_openForm_lcp: new Trend('E_ContactUsPage_openForm_lcp'),
    ContactUsPage_openForm_fcp: new Trend('E_ContactUsPage_openForm_fcp'),
    ContactUsPage_openForm_ttfb: new Trend('E_ContactUsPage_openForm_ttfb'),
    ContactUsPage_openForm_ttlb: new Trend('E_ContactUsPage_openForm_ttlb'),
    ContactUsPage_openForm_completion_time: new Trend('E_ContactUsPage_openForm_completion_time'),
    ContactUsPage_openForm_latency: new Trend('E_ContactUsPage_openForm_latency'),
    ContactUsPage_openForm_dom_interactive: new Trend('E_ContactUsPage_openForm_dom_interactive'),
    ContactUsPage_openForm_network_overhead: new Trend('E_ContactUsPage_openForm_network_overhead'),
    ContactUsPage_openForm_first_response_time: new Trend('E_ContactUsPage_openForm_first_response_time'),
    ContactUsPage_openForm_content_download: new Trend('E_ContactUsPage_openForm_content_download'),
    ContactUsPage_openForm_page_ready: new Trend('E_ContactUsPage_openForm_page_ready'),
    ContactUsPage_openForm_first_interactive: new Trend('E_ContactUsPage_openForm_first_interactive'),


    ContactUsPage_fillForm_lcp: new Trend('F_ContactUsPage_fillForm_lcp'),
    ContactUsPage_fillForm_fcp: new Trend('F_ContactUsPage_fillForm_fcp'),
    ContactUsPage_fillForm_ttfb: new Trend('F_ContactUsPage_fillForm_ttfb'),
    ContactUsPage_fillForm_ttlb: new Trend('F_ContactUsPage_fillForm_ttlb'),
    ContactUsPage_fillForm_completion_time: new Trend('F_ContactUsPage_fillForm_completion_time'),
    ContactUsPage_fillForm_latency: new Trend('F_ContactUsPage_fillForm_latency'),
    ContactUsPage_fillForm_dom_interactive: new Trend('F_ContactUsPage_fillForm_dom_interactive'),
    ContactUsPage_fillForm_network_overhead: new Trend('F_ContactUsPage_fillForm_network_overhead'),
    ContactUsPage_fillForm_first_response_time: new Trend('F_ContactUsPage_fillForm_first_response_time'),
    ContactUsPage_fillForm_content_download: new Trend('F_ContactUsPage_fillForm_content_download'),
    ContactUsPage_fillForm_page_ready: new Trend('F_ContactUsPage_fillForm_page_ready'),
    ContactUsPage_fillForm_first_interactive: new Trend('F_ContactUsPage_fillForm_first_interactive'),




    // LeadershipPage_openFrontlineLeader_lcp: new Trend('LeadershipPage_openFrontlineLeader_lcp'),
    // LeadershipPage_openFrontlineLeader_fcp: new Trend('LeadershipPage_openFrontlineLeader_fcp'),
    // LeadershipPage_openFrontlineLeader_ttfb: new Trend('LeadershipPage_openFrontlineLeader_ttfb'),
    // LeadershipPage_openFrontlineLeader_ttlb: new Trend('LeadershipPage_openFrontlineLeader_ttlb'),
    // LeadershipPage_openFrontlineLeader_completion_time: new Trend('LeadershipPage_openFrontlineLeader_completion_time'),
    // LeadershipPage_openFrontlineLeader_latency: new Trend('LeadershipPage_openFrontlineLeader_latency'),
    // LeadershipPage_openFrontlineLeader_dom_interactive: new Trend('LeadershipPage_openFrontlineLeader_dom_interactive'),
    // LeadershipPage_openFrontlineLeader_network_overhead: new Trend('LeadershipPage_openFrontlineLeader_network_overhead'),
    // LeadershipPage_openFrontlineLeader_first_response_time: new Trend('LeadershipPage_openFrontlineLeader_first_response_time'),
    // LeadershipPage_openFrontlineLeader_content_download: new Trend('LeadershipPage_openFrontlineLeader_content_download'),
    // LeadershipPage_openFrontlineLeader_page_ready: new Trend('LeadershipPage_openFrontlineLeader_page_ready'),
    // LeadershipPage_openFrontlineLeader_first_interactive: new Trend('LeadershipPage_openFrontlineLeader_first_interactive'),


    // LeadershipPage_openFrontlineProgram_lcp: new Trend('LeadershipPage_openFrontlineProgram_lcp'),
    // LeadershipPage_openFrontlineProgram_fcp: new Trend('LeadershipPage_openFrontlineProgram_fcp'),
    // LeadershipPage_openFrontlineProgram_ttfb: new Trend('LeadershipPage_openFrontlineProgram_ttfb'),
    // LeadershipPage_openFrontlineProgram_ttlb: new Trend('LeadershipPage_openFrontlineProgram_ttlb'),
    // LeadershipPage_openFrontlineProgram_completion_time: new Trend('LeadershipPage_openFrontlineProgram_completion_time'),
    // LeadershipPage_openFrontlineProgram_latency: new Trend('LeadershipPage_openFrontlineProgram_latency'),
    // LeadershipPage_openFrontlineProgram_dom_interactive: new Trend('LeadershipPage_openFrontlineProgram_dom_interactive'),
    // LeadershipPage_openFrontlineProgram_network_overhead: new Trend('LeadershipPage_openFrontlineProgram_network_overhead'),
    // LeadershipPage_openFrontlineProgram_first_response_time: new Trend('LeadershipPage_openFrontlineProgram_first_response_time'),
    // LeadershipPage_openFrontlineProgram_content_download: new Trend('LeadershipPage_openFrontlineProgram_content_download'),
    // LeadershipPage_openFrontlineProgram_page_ready: new Trend('LeadershipPage_openFrontlineProgram_page_ready'),
    // LeadershipPage_openFrontlineProgram_first_interactive: new Trend('LeadershipPage_openFrontlineProgram_first_interactive'),



};
