import { Trend } from 'k6/metrics';

export const trends = {

challengespageOpenlcp: new Trend('challengespage_open_lcp'),
challengespageOpenfcp: new Trend('challengespage_open_fcp'),
challengespageOpenttfb: new Trend('challengespage_open_ttfb'),
challengespageOpenttlb: new Trend('challengespage_open_ttlb'),
challengespageOpencompletiontime: new Trend('challengespage_open_completion_time'),
challengespageOpenlatency: new Trend('challengespage_open_latency'),
challengespageOpendominteractive: new Trend('challengespage_open_dom_interactive'),
challengespageOpennetworkoverhead: new Trend('challengespage_open_network_overhead'),
challengespageOpenfirstresponsetime: new Trend('challengespage_open_first_response_time'),
challengespageOpencontentdownload: new Trend('challengespage_open_content_download'),
challengespageOpenready: new Trend('challengespage_open_page_ready'),
challengespageOpenfirstinteractive: new Trend('challengespage_open_first_interactive'),

middlemanagerspageOpenlcp: new Trend('middlemanagerspage_open_lcp'),
middlemanagerspageOpenfcp: new Trend('middlemanagerspage_open_fcp'),
middlemanagerspageOpenttfb: new Trend('middlemanagerspage_open_ttfb'),
middlemanagerspageOpenttlb: new Trend('middlemanagerspage_open_ttlb'),
middlemanagerspageOpencompletiontime: new Trend('middlemanagerspage_open_completion_time'),
middlemanagerspageOpenlatency: new Trend('middlemanagerspage_open_latency'),
middlemanagerspageOpendominteractive: new Trend('middlemanagerspage_open_dom_interactive'),
middlemanagerspageOpennetworkoverhead: new Trend('middlemanagerspage_open_network_overhead'),
middlemanagerspageOpenfirstresponsetime: new Trend('middlemanagerspage_open_first_response_time'),
middlemanagerspageOpencontentdownload: new Trend('middlemanagerspage_open_content_download'),
middlemanagerspageOpenready: new Trend('middlemanagerspage_open_page_ready'),
middlemanagerspageOpenfirstinteractive: new Trend('middlemanagerspage_open_first_interactive'),

ContactUsPage_openForm_lcp: new Trend('ContactUsPage_openForm_lcp'),
ContactUsPage_openForm_fcp: new Trend('ContactUsPage_openForm_fcp'),
ContactUsPage_openForm_ttfb: new Trend('ContactUsPage_openForm_ttfb'),
ContactUsPage_openForm_ttlb: new Trend('ContactUsPage_openForm_ttlb'),
ContactUsPage_openForm_completion_time: new Trend('ContactUsPage_openForm_completion_time'),
ContactUsPage_openForm_latency: new Trend('ContactUsPage_openForm_latency'),
ContactUsPage_openForm_dom_interactive: new Trend('ContactUsPage_openForm_dom_interactive'),
ContactUsPage_openForm_network_overhead: new Trend('ContactUsPage_openForm_network_overhead'),
ContactUsPage_openForm_first_response_time: new Trend('ContactUsPage_openForm_first_response_time'),
ContactUsPage_openForm_content_download: new Trend('ContactUsPage_openForm_content_download'),
ContactUsPage_openForm_page_ready: new Trend('ContactUsPage_openForm_page_ready'),
ContactUsPage_openForm_first_interactive: new Trend('ContactUsPage_openForm_first_interactive'),


ContactUsPage_fillForm_lcp: new Trend('ContactUsPage_fillForm_lcp'),
ContactUsPage_fillForm_fcp: new Trend('ContactUsPage_fillForm_fcp'),
ContactUsPage_fillForm_ttfb: new Trend('ContactUsPage_fillForm_ttfb'),  
ContactUsPage_fillForm_ttlb: new Trend('ContactUsPage_fillForm_ttlb'),
ContactUsPage_fillForm_completion_time: new Trend('ContactUsPage_fillForm_completion_time'),
ContactUsPage_fillForm_latency: new Trend('ContactUsPage_fillForm_latency'),
ContactUsPage_fillForm_dom_interactive: new Trend('ContactUsPage_fillForm_dom_interactive'),
ContactUsPage_fillForm_network_overhead: new Trend('ContactUsPage_fillForm_network_overhead'),
ContactUsPage_fillForm_first_response_time: new Trend('ContactUsPage_fillForm_first_response_time'),
ContactUsPage_fillForm_content_download: new Trend('ContactUsPage_fillForm_content_download'),
ContactUsPage_fillForm_page_ready: new Trend('ContactUsPage_fillForm_page_ready'),
ContactUsPage_fillForm_first_interactive: new Trend('ContactUsPage_fillForm_first_interactive'),

HomePage_open_lcp: new Trend('HomePage_open_lcp'),
HomePage_open_fcp: new Trend('HomePage_open_fcp'),
HomePage_open_ttfb: new Trend('HomePage_open_ttfb'),
HomePage_open_ttlb: new Trend('HomePage_open_ttlb'),
HomePage_open_completion_time: new Trend('HomePage_open_completion_time'),
HomePage_open_latency: new Trend('HomePage_open_latency'),
HomePage_open_dom_interactive: new Trend('HomePage_open_dom_interactive'),
HomePage_open_network_overhead: new Trend('HomePage_open_network_overhead'),
HomePage_open_first_response_time: new Trend('HomePage_open_first_response_time'),
HomePage_open_content_download: new Trend('HomePage_open_content_download'),
HomePage_open_page_ready: new Trend('HomePage_open_page_ready'),
HomePage_open_first_interactive: new Trend('HomePage_open_first_interactive'),


LeadershipPage_openleadershipProgram_lcp: new Trend('LeadershipPage_openleadershipProgram_lcp'),
LeadershipPage_openleadershipProgram_fcp: new Trend('LeadershipPage_openleadershipProgram_fcp'),
LeadershipPage_openleadershipProgram_ttfb: new Trend('LeadershipPage_openleadershipProgram_ttfb'),
LeadershipPage_openleadershipProgram_ttlb: new Trend('LeadershipPage_openleadershipProgram_ttlb'),
LeadershipPage_openleadershipProgram_completion_time: new Trend('LeadershipPage_openleadershipProgram_completion_time'),
LeadershipPage_openleadershipProgram_latency: new Trend('LeadershipPage_openleadershipProgram_latency'),
LeadershipPage_openleadershipProgram_dom_interactive: new Trend('LeadershipPage_openleadershipProgram_dom_interactive'),
LeadershipPage_openleadershipProgram_network_overhead: new Trend('LeadershipPage_openleadershipProgram_network_overhead'),
LeadershipPage_openleadershipProgram_first_response_time: new Trend('LeadershipPage_openleadershipProgram_first_response_time'),
LeadershipPage_openleadershipProgram_content_download: new Trend('LeadershipPage_openleadershipProgram_content_download'),
LeadershipPage_openleadershipProgram_page_ready: new Trend('LeadershipPage_openleadershipProgram_page_ready'),
LeadershipPage_openleadershipProgram_first_interactive: new Trend('LeadershipPage_openleadershipProgram_first_interactive'),

LeadershipPage_openFrontlineLeader_lcp: new Trend('LeadershipPage_openFrontlineLeader_lcp'),
LeadershipPage_openFrontlineLeader_fcp: new Trend('LeadershipPage_openFrontlineLeader_fcp'),
LeadershipPage_openFrontlineLeader_ttfb: new Trend('LeadershipPage_openFrontlineLeader_ttfb'),
LeadershipPage_openFrontlineLeader_ttlb: new Trend('LeadershipPage_openFrontlineLeader_ttlb'),
LeadershipPage_openFrontlineLeader_completion_time: new Trend('LeadershipPage_openFrontlineLeader_completion_time'),
LeadershipPage_openFrontlineLeader_latency: new Trend('LeadershipPage_openFrontlineLeader_latency'),
LeadershipPage_openFrontlineLeader_dom_interactive: new Trend('LeadershipPage_openFrontlineLeader_dom_interactive'),
LeadershipPage_openFrontlineLeader_network_overhead: new Trend('LeadershipPage_openFrontlineLeader_network_overhead'),
LeadershipPage_openFrontlineLeader_first_response_time: new Trend('LeadershipPage_openFrontlineLeader_first_response_time'),
LeadershipPage_openFrontlineLeader_content_download: new Trend('LeadershipPage_openFrontlineLeader_content_download'),
LeadershipPage_openFrontlineLeader_page_ready: new Trend('LeadershipPage_openFrontlineLeader_page_ready'),
LeadershipPage_openFrontlineLeader_first_interactive: new Trend('LeadershipPage_openFrontlineLeader_first_interactive'),


LeadershipPage_openFrontlineProgram_lcp: new Trend('LeadershipPage_openFrontlineProgram_lcp'),
LeadershipPage_openFrontlineProgram_fcp: new Trend('LeadershipPage_openFrontlineProgram_fcp'),
LeadershipPage_openFrontlineProgram_ttfb: new Trend('LeadershipPage_openFrontlineProgram_ttfb'),
LeadershipPage_openFrontlineProgram_ttlb: new Trend('LeadershipPage_openFrontlineProgram_ttlb'),
LeadershipPage_openFrontlineProgram_completion_time: new Trend('LeadershipPage_openFrontlineProgram_completion_time'),
LeadershipPage_openFrontlineProgram_latency: new Trend('LeadershipPage_openFrontlineProgram_latency'),
LeadershipPage_openFrontlineProgram_dom_interactive: new Trend('LeadershipPage_openFrontlineProgram_dom_interactive'),
LeadershipPage_openFrontlineProgram_network_overhead: new Trend('LeadershipPage_openFrontlineProgram_network_overhead'),
LeadershipPage_openFrontlineProgram_first_response_time: new Trend('LeadershipPage_openFrontlineProgram_first_response_time'),
LeadershipPage_openFrontlineProgram_content_download: new Trend('LeadershipPage_openFrontlineProgram_content_download'),
LeadershipPage_openFrontlineProgram_page_ready: new Trend('LeadershipPage_openFrontlineProgram_page_ready'),
LeadershipPage_openFrontlineProgram_first_interactive: new Trend('LeadershipPage_openFrontlineProgram_first_interactive'),



};
